"""empty message

Revision ID: e49bbd0902c5
Revises: d07863eb3451
Create Date: 2018-09-29 21:11:10.722450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e49bbd0902c5'
down_revision = 'd07863eb3451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fiction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiction_name', sa.String(length=128), nullable=True),
    sa.Column('fiction_auth', sa.String(length=64), nullable=True),
    sa.Column('fiction_real_url', sa.String(length=140), nullable=True),
    sa.Column('fiction_id', sa.String(length=100), nullable=True),
    sa.Column('fiction_img', sa.String(length=140), nullable=True),
    sa.Column('fiction_comment', sa.String(length=140), nullable=True),
    sa.Column('update', sa.String(length=400), nullable=True),
    sa.Column('new_content', sa.String(length=1024), nullable=True),
    sa.Column('new_url', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fiction_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiction_url', sa.String(length=255), nullable=True),
    sa.Column('fiction_content', sa.Text(), nullable=True),
    sa.Column('fiction_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fiction_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiction_name', sa.String(length=255), nullable=True),
    sa.Column('fiction_id', sa.String(length=255), nullable=True),
    sa.Column('fiction_lst_url', sa.String(length=255), nullable=True),
    sa.Column('fiction_lst_name', sa.String(length=255), nullable=True),
    sa.Column('fiction_real_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fiction_list')
    op.drop_table('fiction_content')
    op.drop_table('fiction')
    # ### end Alembic commands ###
